### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by yashh** [defunkt/hurl#13]
When a User sign up the user is created in the redis but does n't login automatically. I tried to signup on http://hurl.it as well and did n't work. Is it me ?

When I fire up rake start which starts shotgun & redis, Ctrl-C only kills redis, shotgun runs in the background. I have to kill it with sudo kill <pid>. Is it the proper way to kill it?

**Comment by sjl** [comment]
Both of these are also problems for me.  I can't log in either, I haven't really tried to figure out what's wrong though.

For the second problem, I usually run `killall ruby` in another terminal, which only works because I'm not a ruby developer and don't have other ruby processes that I care about keeping.  It would be really nice if `^C` killed Redis _and_ Rack.

**Comment by filiptepper** [comment]
Same issue here, cannot signup/login, both on hurl.it and locally.

**Comment by defunkt** [comment]
Fix login / session by cleaning up key namespacing. Closed by b4ee4b609aa41e6e923e057807918ecd536fb64d
